import { LockReset } from "@mui/icons-material";
import product from "../../../public/products/T-shirt Men.png";
export const products = [
  {
    id: 1,
    name: "Women's Fashion",
    price: 140,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
    },
  {
    id: 2,
    name: "Denim Blue Jeans",
    price: 140,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
  {
    id: 3,
    name: "Yellow Casual Sweater",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
  },
  {
    id: 4,
    name: "Nike Red",
    price: 210,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
  {
    id: 5,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
  },
  {
    id: 6,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
  {
    id: 7,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
  },
  {
    id: 8,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
  {
    id: 9,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
  },
  {
    id: 10,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
  {
    id: 11,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Women",
    discription: "the best product in the world",
  },
  {
    id: 12,
    name: "North Star Blue",
    price: 110,
    rating: 4,
    reviews: 0,
    image: product,
    category: "Men",
    discription: "the best product in the world",
  },
];
